name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file ../dingtaiback/customer-manage/pom.xml
    - name: SCP Command to Transfer Files
      uses: appleboy/scp-action@v0.0.6
      with:
        host: ${{ secrets.host }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        target: /usr/local/dingtai/backend
        source: ./dingtaiback/customer-manage/*
        rm: true

